language: node_js
node_js:
  - '6'
  - 'node'

branches:
  except:
    -experimental

after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'

notifications:
  email:
    on_success: never
    on_failure: change
